version: '2'

volumes:
  migrated:

services:

  bootstrap:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: ./docker/bootstrap/Dockerfile
    image: bootstrap:latest
    container_name: bootstrap
    command: bash -c ./bootstrap.sh
    volumes:
      - ./src/opt/callowayart/bin/post:/opt/callowayart/bin/post
      - ./src/opt/callowayart/task/migrate.rake:/opt/callowayart/task/migrate.rake
      - migrated:/opt/callowayart/wp-content/uploads/migrated
    environment:
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
      DOMAIN: ${DOMAIN}
      MIGRATION_LIMIT: ${MIGRATION_LIMIT}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASS}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - ./src/etc/mysql/conf.d/general.cnf:/etc/mysql/conf.d/general.cnf:ro
    container_name: db

  exporter:
    image: ${ORG}/exporter:${SHA}
    restart: always
    build:
      context: .
      dockerfile: ./docker/exporter/Dockerfile
    environment:
      WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    ports:
      - 8888
    container_name: exporter

  varnish:
    image: ${ORG}/varnish:${SHA}
    links:
      - wordpress
    ports:
      - ${PORT}:${PORT}
    restart: always
    build:
      context: .
      dockerfile: ./docker/varnish/Dockerfile
      args:
        PORT: ${PORT}
    environment:
      VARNISH_MEMORY: 256M
    container_name: varnish

  wordpress:
    image: ${ORG}/wordpress:${SHA}
    depends_on:
      - db
    ports:
      - ${PORT}
    restart: always
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        PORT: ${PORT}
    command: /opt/callowayart/start.sh
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASS}
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
    volumes:
      - migrated:/var/www/html/wp-content/uploads/migrated
      - ./build/wordpress/wp-content:/var/www/html/wp-content:rw
    container_name: wordpress
