version: '2'

volumes:
  migrated:

services:

  bootstrap:
    depends_on:
      - db
    links:
      - db
    build:
      context: ./
      dockerfile: ./docker/bootstrap/Dockerfile
    image: bootstrap:latest
    container_name: bootstrap
    command: bash -c ./bootstrap.sh
    volumes:
      - migrated:/opt/callowayart/wp-content/uploads/migrated
    environment:
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
      DOMAIN: ${DOMAIN}
      MIGRATION_LIMIT: ${MIGRATION_LIMIT}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes:
      - ./src/etc/mysql/conf.d/general.cnf:/etc/mysql/conf.d/general.cnf:ro
    container_name: db

  varnish:
    image: ${ORG}/varnish:${SHA}
    links:
      - wordpress
    ports:
      - ${PORT}:${PORT}
    restart: always
    build:
      context: .
      dockerfile: ./docker/varnish/Dockerfile
      args:
        PORT: ${PORT}
    environment:
      VARNISH_MEMORY: 256M
    container_name: varnish

  wordpress:
    image: ${ORG}/wordpress:${SHA}
    depends_on:
      - db
    ports:
      - 8080:${PORT}
    restart: always
    build:
      context: ./
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        PORT: ${PORT}
    command: /opt/callowayart/start.sh
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
    volumes:
      - migrated:/var/www/html/wp-content/uploads/migrated
    container_name: wordpress
