version: '2'

services:
  bootstrap:
    depends_on:
      - db
    links:
      - db
    build:
     context: ./../../
     dockerfile: ./docker/bootstrap/Dockerfile
    image: bootstrap
    command: bash -c ./bootstrap.sh
    volumes:
      - ./src/opt/callowayart/bootstrap.sh:/opt/callowayart/bootstrap.sh
    container_name: migration-bootstrap
    environment:
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    container_name: migration-db
  callowayart:
    image: ${REPOSITORY}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: always
    build:
      context: ./
      dockerfile: ./docker/callowayart/Dockerfile
      args:
        PORT: ${PORT}
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
      MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
    container_name: callowayart
